/* eslint-disable @next/next/google-font-display */
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
    return (
        <Html lang="en" style={{height: '100%'}}>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="initial-scale=1, width=device-width"/>
                <link rel="icon" href="/marvel-logo.png"/>
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto"  />
            </Head>
            <body style={{height: '100%'}}>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}